### ISSUE TITLE
TypeError: Cannot read property 'Subject' of undefined

### ISSUE THREAD

**Issue by ccerrato147** [MichalZalecki/connect-rxjs-to-react#7]
I download the program, ran npm install and then npm run build but when I run the tests and load it on the browser I get the error "TypeError: Cannot read property 'Subject' of undefined". It seems like it's not loading the rxjs package to the Rx.js variable. I already tried re-installing but didn't work.

The full error stack is:

TypeError: Cannot read property 'Subject' of undefined
    at createAction (/Users/ccerrato147/Projects/connect-rxjs-to-react/src/state/RxState.js:6:14)
    at /Users/ccerrato147/Projects/connect-rxjs-to-react/src/state/RxState.js:10:63
    at Array.reduce (native)
    at createActions (/Users/ccerrato147/Projects/connect-rxjs-to-react/src/state/RxState.js:10:22)
    at Object.<anonymous> (/Users/ccerrato147/Projects/connect-rxjs-to-react/src/actions/counterActions.js:3:16)
    at Module._compile (module.js:571:32)
    at loader (/Users/ccerrato147/Projects/connect-rxjs-to-react/node_modules/babel-register/lib/node.js:144:5)
    at require.extensions.(anonymous function) (/Users/ccerrato147/Projects/connect-rxjs-to-react/node_modules/babel-register/lib/node.js:154:7)
    at extensions.(anonymous function) (/Users/ccerrato147/Projects/connect-rxjs-to-react/node_modules/require-precompiled/index.js:16:3)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/ccerrato147/Projects/connect-rxjs-to-react/node_modules/ava/lib/test-worker.js:92:3)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ccerrato147/Projects/connect-rxjs-to-react/src/reducers/CounterReducer.spec.js:3:1)
    at Module._compile (module.js:571:32)
    at extensions.(anonymous function) (/Users/ccerrato147/Projects/connect-rxjs-to-react/node_modules/require-precompiled/index.js:13:11)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/ccerrato147/Projects/connect-rxjs-to-react/node_modules/ava/lib/test-worker.js:92:3)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ccerrato147/Projects/connect-rxjs-to-react/node_modules/ava/lib/test-worker.js:96:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
/Users/ccerrato147/Projects/connect-rxjs-to-react/src/state/RxState.js:42
  return new _rxjs2.default.Subject();

**Comment by MichalZalecki** [comment]
I've just tested and it works fine. Make sure you have up-to-date version of node/npm installed. I'd need more details to help you.

**Comment by ccerrato147** [comment]
Yeah, I think that might be it. I didn't test it anymore since I ended picking another base project to start. Thanks for the quick reply though!
